language: php

sudo: required
dist: xenial

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 5.6
  include:
    - php: 7.0
      env: ZEND_BACKEND="--backend=ZendEngine3"
    - php: 7.1
      env: ZEND_BACKEND="--backend=ZendEngine3"

git:
  depth: 1

cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - .temp
    - vendor
    - ~/.ccache
    - ~/.composer/cache
    - ~/cphalcon

services:
  - sqlite3
  - mysql
  - postgresql

env:
  global:
    - TEST_DB_HOST="127.0.0.1"
    - TEST_DB_USER="phorm_generator_test"
    - TEST_DB_NAME="phorm_generator_test"
    - ZEND_DONT_UNLOAD_MODULES=1
    - CC="ccache gcc"
    - PHPIZE_BIN="$(which phpize 2> /dev/null || which phpize5 2> /dev/null)"

before_install:
  #- export PATH=$PATH:~/bin;
  - export PHP_MAJOR="$(echo $TRAVIS_PHP_VERSION | cut -d '.' -f 1,2)"
  - composer install --prefer-source --no-interaction
  - vendor/bin/install-phalcon.sh 3.0.x
  - travis_retry composer --prefer-source install
  - '( zephir fullclean && zephir generate $ZEND_BACKEND )'

before_script:
  - phpenv config-add tests/php.ini

script:
  - vendor/bin/phpunit -c test/phpunit.xml --debug

notifications:
  email:
    - lazos@lazos.me

addons:
  apt:
    packages:
      - gdb
      - re2c
