language: php

sudo: required
dist: xenial

php:
  - 5.6
  - 7.0

git:
  depth: 1

cache:
  directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

services:
  - sqlite3
  - mysql
  - postgresql

before_install:
  - composer install --prefer-source --no-interaction
  - vendor/bin/install-phalcon.sh 3.0.x

before_script:
  - phpenv config-add tests/php.ini

script:
  - vendor/bin/phpunit -c phpunit.xml --debug

notifications:
  email:
    - lazos@lazos.me

addons:
  apt:
    packages:
      - gdb
      - re2c
